# Generated by Django 4.0.1 on 2022-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='img',
            field=models.FilePathField(path='/static/img'),
        ),
    ]
