# Generated by Django 4.0.1 on 2022-02-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_img_qrcode_img_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='user_id',
            new_name='user',
        ),
    ]
